name: sc25_ncs
channels:
    - pytorch
dependencies:
    - python=3.9
    - pandas=2.2.2
    - numpy=1.26.4
    - llvmlite=0.42.0
    - pytorch=2.3.0
    - scikit-learn=1.4.2
    - matplotlib=3.9.2
    - seaborn=0.13.2
    - scipy=1.13.1
    - tqdm=4.66.5
